### PR TITLE
add XTTSv2

### PR DESCRIPTION
**Pull request by kanttouchthis**

### CODE REVIEW

**Comment by oobabooga** [comment]
Could you submit the extension code to the main repository as a PR? I want to add this as a built-in.

**Comment by kanttouchthis** [comment]
> Could you submit the extension code to the main repository as a PR? I want to add this as a built-in.

I'm working on that. Only problem is TTS requires --no-dependencies in order to work with the webui requirements and afaik you can't add --no-dependencies in a requirements.txt. would a bat / sh script be ok for installation?

**Comment by oobabooga** [comment]
The extensions requirements are installed before the web ui requirements in new installs. I assume some of the coqui requirements are overwritten by this, but maybe it will work anyway?

For existing installs, I could add a warning in the extension code in a `try: import ... except:` block with the correct installation command for people to copy and paste.

**Comment by kanttouchthis** [comment]
the issue is that coqui will install specific versions of many libraries, which would then be overwritten by the web ui requirements, causing longer install time and potential version conflicts. I have only been able to get it to work by manually installing TTS' requirements without version constraints and then installing TTS

**Comment by kanttouchthis** [comment]
I tested it and it works on windows at least. I made a PR

**Comment by oobabooga** [comment]
Thanl you! I'll try to test it tomorrow.

**Pull request merged**
